version: "3"
services:
  mysql:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
  app:
    build: .
    volumes:
      - .:/caian_app
      - public-data:/caian_app/public
      - tmp-data:/caian_app/tmp
    tty: true
    stdin_open: true
    depends_on:
      - mysql
    user: root
    environment:
      DB_HOSTNAME: mysql
      DB_USERNAME: root
      DB_PASSWORD: password
  nginx:
    build:
      context: ./containers/nginx
    volumes:
      - public-data:/caian_app/public
      - tmp-data:/caian_app/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  db-data:
  public-data:
  tmp-data:
