version: "3"
services:
  mysql:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    volumes:
      - ./apps/backend/mysql-init:/docker-entrypoint-initdb.d
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    tty: true
    stdin_open: true
  app:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./apps/backend
        target: /caian-app
        consistency: delegated
      - ./apps/backend/containers/nginx/nginx.conf:/etc/nginx/templates/nginx.conf
      - tmp-data:/caian-app/tmp
      - public-data:/caian-app/public
    tty: true
    stdin_open: true
    depends_on:
      - mysql
    user: root
    environment:
      DB_HOSTNAME: mysql
      DB_USERNAME: root
      DB_PASSWORD:
    command: /bin/sh -c "bundle install && yarn install && rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        target: /caian-frontend
        source: ./apps/frontend
    ports:
      - "3001:3000"
    command: /bin/sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
  nginx:
    build:
      context: ./apps/backend/containers/nginx
    ports:
      - 80:80
    volumes:
      - ./apps/backend/containers/nginx/nginx.conf:/etc/nginx/templates/nginx.conf
      - nginx-logs:/var/log/nginx
      - tmp-data:/caian-app/tmp
      - public-data:/caian-app/public
    depends_on:
      - app
volumes:
  mysql-data:
    driver: local
  tmp-data:
    driver: local
  public-data:
    driver: local
  nginx-logs:
    driver: local
networks:
  default:
    name: caian-network
