version: "3"
volumes:
    data:
services:
  web:
    # コンテナ名の指定
    container_name: caian_web
    # Dockerfile のあるディレクトリのパスを指定「.」で同じフォルダ内
    build: .
    # ポートの指定（外部からのアクセス時のポート：Dockerコンテナからアクセス時のポート）
    ports:
      - "3000:3000"
    # データの参照先（ホスト側のカレントディレクトリにマウントする）
    volumes:
      - .:/caian_app
    # 出力結果を見やすくする
    tty: true
    # 入力を可能にする
    stdin_open: true
    # # デフォルトのコマンド指定（Rails特有の問題解消とRails立ち上げを指定している）
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # 依存関係の指定（dbが起動した後に、webが起動するようになる）
    depends_on:
      - db
    links:
      - db
  db:
    # コンテナ名の指定
    container_name: caian_db
    # イメージの指定
    image: mysql:5.7.39
    # ポートの指定（外部からのアクセス時のポート：Dockerコンテナからアクセス時のポート）
    ports:
      - "3060:3060"
    # ボリュームとは、データを永続化できる場所のこと
    # コンテナ内部にデータ(ファイル)を保存しても、コンテナ破棄すると消える
    volumes:
      - data:/var/lib/mysql
    # 環境変数の指定（初期設定値）
    environment:
      MYSQL_ROOT_PASSWORD: <%= ENV['DB_PASSWORD'] %>
