version: "3"
services:
  rails:
    container_name: caian_rails
    build: .
    volumes:
      - .:/caian_app
      - public-data:/caian_app/public
      - tmp-data:/caian_app/tmp
    tty: true
    stdin_open: true
    depends_on:
      - db
    user: root
    environment:
      DB_HOSTNAME: caian_db
      DB_USERNAME: docker
      DB_PASSWORD: password

  db:
    container_name: caian_db
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_HOST: localhost
      MYSQL_ROOT_PASSWORD: <%= ENV['DB_PASSWORD'] %>

  web:
    build:
      context: ./containers/nginx
    volumes:
      - public-data:/caian_app/public
      - tmp-data:/caian_app/tmp
    ports:
      - 80:80
    depends_on:
      - rails

volumes:
  db:
    driver: local
  public-data:
  tmp-data:
  log-data:
