version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t caian .
      - docker tag caian 913895474453.dkr.ecr.ap-northeast-1.amazonaws.com/caian
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 913895474453.dkr.ecr.ap-northeast-1.amazonaws.com/caian
