name: Send merge results to Slack

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  notify_merge_result:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    # 通知内容を設定
    - name: Set notification message
      id: set_msg
      run: |
        if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
          echo "::set-output name=result:::github: Merge Result: merged successfully\n\n${{ github.event.pull_request.html_url }}"
        else
          echo "::set-output name=result:::github: Merge Result: merge failed\n\n${{ github.event.pull_request.html_url }}"
        fi

    # Slackへの通知
    - name: Notify Slack
      uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: |
          {
            "text": "${{ steps.set_msg.outputs.result }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ steps.set_msg.outputs.result }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
