name: Check OPEN PR

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Check Open PR
        id: check_pr
        run: |
          OPEN_PR=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?state=open")
          echo "OPEN_PR: $OPEN_PR"
          echo "OPEN_PR_COUNT=$(echo $OPEN_PR | jq '. | length')" >> $GITHUB_ENV

      - name: Get previous run time
        id: previous-run-time
        run: |
          PREVIOUS_RUN_TIME=$(cat .github/previous_run_time.txt || echo "1970-01-01T00:00:00Z")
          echo "PREVIOUS_RUN_TIME=$PREVIOUS_RUN_TIME" >> $GITHUB_ENV

      - name: Save current time for next run
        run: echo $(date -u +%Y-%m-%dT%H:%M:%SZ) > .github/previous_run_time.txt

      - name: Get PRs URL
        id: get_pr_urls
        if: env.OPEN_PR_COUNT != '0'
        run: |
          PR_URLS=$(echo $OPEN_PR | jq -r --arg PREVIOUS_RUN_TIME "$PREVIOUS_RUN_TIME" \
          '[.[] | select(.created_at >= $PREVIOUS_RUN_TIME) | .html_url] | join("\n- ")')
          echo "PR_URLS=- $PR_URLS" >> $GITHUB_ENV
          echo "::set-output name=pr_urls::- $PR_URLS"

      - name: Notify Slack
        if: env.OPEN_PR_COUNT != '0'
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "text": "OPENになっているPRがあります",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<@U04KJ2MBSFR> OPENになっているPRがあるので、レビューをお願いします！\n\n${{ steps.get_pr_urls.outputs.pr_urls }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
