name: Check OPEN PR

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set GH_TOKEN environment variable
        run: echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Get PRs created after 9 AM previous day
        id: get_prs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Calculate previous day's 9:00 AM in UTC
          PREVIOUS_DATE=$(date -u -d 'yesterday 09:00' +%Y-%m-%dT%H:%M:%SZ)
          echo "PREVIOUS_DATE: $PREVIOUS_DATE"

          # Fetch all open PRs
          PRS=$(gh pr list --json number,title,createdAt,url)
          echo "All PRs: $PRS"

          # Filter PRs created after 9 AM previous day
          NEW_PRS=$(echo "$PRS" | jq --arg PREVIOUS_DATE "$PREVIOUS_DATE" '[.[] | select(.createdAt >= $PREVIOUS_DATE)]')
          echo "Filtered PRs: $NEW_PRS"

          # Extract titles and URLs
          PR_URLS_TITLES=$(echo "$NEW_PRS" | jq -r '.[] | "<\(.url)|#\(.number) \(.title)>"')
          echo "PR_URLS_TITLES: $PR_URLS_TITLES"

          # Save for later steps
          echo "PR_URLS_TITLES=$PR_URLS_TITLES" >> $GITHUB_ENV

      - name: Notify Slack
        if: env.PR_URLS_TITLES != ''
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "text": "前日の9時以降に作成された新規PRがあります",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<@U04KJ2MBSFR>/n/n :github: 前回から新規でOPENになったPRがあります！\n\n${{ env.PR_URLS_TITLES }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
