name: Daily Bundle Update PR

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  bundle-update:
    runs-on: ubuntu-latest

    env:
      BACKEND_DIR: 'apps/backend'

    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.3'

      - name: Set DATE variable
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Ensure main is up to date
        run: |
          git switch main
          git pull origin main

      - name: Update Gemfile.lock
        run: |
          echo "--- git branch ---"
          git branch
          cd ${{ env.BACKEND_DIR }}
          bundle update

          echo "--- git status ---"
          git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.create_token.outputs.token }}
          base: main
          branch: update-bundle-${{ env.DATE }}
          add-paths: ${{ env.BACKEND_DIR }}/Gemfile.lock
          commit-message: "Update Gemfile.lock on ${{ env.DATE }}"
          committer	: Display Name <${OWNER_EMAIL}>
          reviewers: aki366
          title: "Update Gemfile.lock on ${{ env.DATE }}"
          body: "Automated update of Gemfile.lock by GitHub Actions"
          draft: false
