name: Daily Bundle Update PR

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  bundle-update:
    runs-on: ubuntu-latest

    env:
      BACKEND_DIR: 'apps/backend'
      DATE: $(date +'%Y%m%d')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.3'

      - name: Update dependencies
        run: |
          cd ${{ env.BACKEND_DIR }}
          bundle update

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b update-bundle-${{ env.DATE }}
          git add ${{ env.BACKEND_DIR }}/Gemfile.lock
          git commit -m "Update Gemfile.lock ${{ env.DATE }}"
          git pull --rebase origin update-bundle-${{ env.DATE }} || true
          git push origin update-bundle-${{ env.DATE }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update Gemfile.lock
          branch: update-bundle-${{ env.DATE }}
          title: "Update Gemfile.lock on ${{ env.DATE }}"
          body: "Automated update of Gemfile.lock by GitHub Actions"
