name: Daily Bundle Update PR

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  bundle-update:
    runs-on: ubuntu-latest

    env:
      BACKEND_DIR: 'apps/backend'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.3'

      - name: Set DATE variable
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Ensure main is up to date
        run: |
          git fetch origin
          git switch main
          git pull origin main

      - name: Rebase update-bundle branch onto main
        run: |
          git checkout -b update-bundle-${{ env.DATE }}

      - name: Update Gemfile.lock
        run: |
          echo "--- git branch ---"
          git branch
          cd ${{ env.BACKEND_DIR }}
          bundle update

          echo "--- git status ---"
          git status
          git add Gemfile.lock
          git commit -m "Update Gemfile.lock on ${{ env.DATE }}"
          git push origin update-bundle-${{ env.DATE }}

          echo "--- git log --oneline -n 5 ---"
          git log --oneline -n 5

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: update-bundle-${{ env.DATE }}
          title: "Update Gemfile.lock on ${{ env.DATE }}"
          body: "Automated update of Gemfile.lock by GitHub Actions"
          draft: false
