name: Daily Bundle Update PR

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  bundle-update:
    runs-on: ubuntu-latest

    env:
      BACKEND_DIR: 'apps/backend'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.3'

      - name: Set DATE variable
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Check if Pull Request already exists
        id: check_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git fetch origin main
          if git diff origin/main..update-bundle-${{ env.DATE }} --quiet; then
            echo "--- No differences with main branch ---"
          else
            echo "--- Differences found with main branch ---"
            echo "pr_needed=true" >> $GITHUB_ENV
          fi

          PR_EXISTS=$(gh pr list --head update-bundle-${{ env.DATE }} --state open --json number --jq '.[0].number')
          if [ -z "$PR_EXISTS" ]; then
            echo "pr_exists=false" >> $GITHUB_ENV
          else
            echo "pr_exists=true" >> $GITHUB_ENV
          fi

          if git ls-remote --exit-code --heads origin update-bundle-${{ env.DATE }}; then
            git fetch origin update-bundle-${{ env.DATE }}:update-bundle-${{ env.DATE }}
            git checkout update-bundle-${{ env.DATE }}
          else
            git checkout -b update-bundle-${{ env.DATE }}
          fi

      - name: Update Gemfile.lock
        run: |
          echo "--- git branch ---"
          git branch
          cd ${{ env.BACKEND_DIR }}
          bundle update

          echo "--- git status ---"
          git status
          git add Gemfile.lock

          if git diff --cached --quiet; then
            echo "--- No changes to commit ---"
          else
            git commit -m "Update Gemfile.lock ${{ env.DATE }}"
            git pull --rebase origin update-bundle-${{ env.DATE }} || true
            git push origin update-bundle-${{ env.DATE }}
            echo "chnges to commit"
          fi

          echo "--- git log --oneline -n 5 ---"
          git log --oneline -n 5

      - name: Create Pull Request
        if: env.pr_exists == 'false' && env.pr_needed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update Gemfile.lock
          base: main
          branch: update-bundle-${{ env.DATE }}
          title: "Update Gemfile.lock on ${{ env.DATE }}"
          body: "Automated update of Gemfile.lock by GitHub Actions"
          draft: false
