name: Get outdated wiki pages

on:
  schedule:
    - cron: '12 5 * * *' # This runs every day at 14:12 JST

jobs:
  check-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout wiki repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki

    - name: Check for old updates and add to the list
      run: |
        echo "" > MaintenanceList.md

        echo "| Pages | Last update |" >> MaintenanceList.md
        echo "| --- | --- |" >> MaintenanceList.md

        OFFSET_DAYS=10
        ONE_DAY_AGO_DATE=$(TZ="Asia/Tokyo" date -d "$OFFSET_DAYS days ago" +'%Y-%m-%d %H:%M:%S')
        echo $ONE_DAY_AGO_DATE

        for file in *; do
          FILE_DATE=$(git log -1 --pretty=format:'%ad' --date=format:'%Y-%m-%d %H:%M:%S' -- "$file")
          echo $FILE_DATE
          if [[ ! "$file" == "MaintenanceList.md" ]] && [[ "$FILE_DATE" < "$ONE_DAY_AGO_DATE" ]]; then
            FILE_WITHOUT_EXTENSION=${file%.md}
            echo "| [$file](https://github.com/aki366/caian-app/wiki/$file) | $(echo $FILE_DATE | cut -d ' ' -f 1) |" >> MaintenanceList.md
            echo "file :" $file " FILE_WITHOUT_EXTENSION :" $FILE_WITHOUT_EXTENSION
          fi
        done

        # If changes exist, commit and push
        if [[ `git status --porcelain` ]]; then
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add MaintenanceList.md
          git commit -m "Update MaintenanceList"
          git push origin master
        fi
