name: Send test results to Slack

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  run_spec:
    name: RSpec

    # ジョブを実行する仮想マシンを選択（ubuntu/macOS/Windows)
    runs-on: ubuntu-latest

    steps:
    # actions/checkoutリポジトリのaction.ymlを利用する
    - uses: actions/checkout@v1 # https://github.com/actions/checkout/blob/master/action.yml
        # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsuses
        #   @~でバージョンやブランチ、コミットIDを指定できる
        #   自リポジトリのaction.ymlがあるディレクトリを相対パスで指定することもできる
        #     ex. uses: ./.github/actions/my-action
        #   Dockerhubのイメージを利用することもできる
        #     ex. uses: docker://alpine:3.8
    - name: Set up Ruby 2.6
      # actions/checkoutリポジトリのaction.ymlを利用する
      uses: actions/setup-ruby@v1 # https://github.com/actions/setup-ruby/blob/master/action.yml
      with:
        ruby-version: 2.6.x
    - name: Test with Rspec
      run: |
        gem install bundler
        bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
        bundle exec rspec
      with:
        payload: |
          {
            "text": ":github: テスト結果: ${{ job.status }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":github: テスト結果: ${{ job.status }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Author: <https://github.com/${{ github.event.sender.login }}|@${{ github.event.sender.login }}>"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     timeout-minutes: 10

#     steps:
#       # Check out theis repo
#       - uses: actions/checkout@v2
#       - run: echo "GitHub push test"
#       # Start a Slack workflow using a webhook trigger
#       # https://github.com/slackapi/slack-github-action
#       - name: Send GitHub Action trigger data to Slack workflow
#         id: slack
#         uses: slackapi/slack-github-action@v1.16.0
#         with:
#           payload: |
#             {
#               "text": ":github: テスト結果: ${{ job.status }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
#               "blocks": [
#                 {
#                   "type": "section",
#                   "text": {
#                     "type": "mrkdwn",
#                     "text": ":github: テスト結果: ${{ job.status }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
#                   }
#                 },
#                 {
#                   "type": "context",
#                   "elements": [
#                     {
#                       "type": "mrkdwn",
#                       "text": "Author: <https://github.com/${{ github.event.sender.login }}|@${{ github.event.sender.login }}>"
#                     }
#                   ]
#                 }
#               ]
#             }
#         env:
#           SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}