name: Auto PR Labeler

on:
  pull_request:
    types: [opened]

jobs:
  label_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Add label if title contains specific strings
        run: |
          if [[ "${{ github.event.pull_request.title }}" == "Update Gemfile.lock"* ]]; then
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{"labels":["manual_rspec"]}' \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels
          fi

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "text": "PRがOPENされました",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@aki PRがOPENされました"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
