name: Send RSpec results to Slack

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  run_spec:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true

      - name: Budle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

       - name: Setup Database
        run: |
          cp config/database.yml.ci config/database.yml
          sudo /etc/init.d/mysql start
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Test with Rspec
        run: bundle exec rspec -f d --dry-run --order defined