name: Send RSpec results to Slack

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  run_spec:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
      - name: Test with Rspec
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rspec