name: Send RSpec results to Slack

on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'apps/backend/**'
  pull_request:
    branches:
      - main
      - release
      - develop
    paths:
    - 'apps/backend/**'

jobs:
  run_spec:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Bundler and gem install
        run: |
          gem install bundler
          cd apps/backend
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Yarn install
        run: yarn install --check-files

      - name: Database create and migrate
        run: |
          cd apps/backend
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Test with Rspec
        continue-on-error: true # Add this to continue even if the test fails
        id: rspec_test  # Add this to reference this step later
        run: bundle exec rspec
