name: Send RSpec results to Slack

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  run_spec:
    # name: RSpec
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v2
        with:
          ruby-version: 3.0.3
      - name: Test with Rspec
        run: bundle exec rspec