name: RuboCop Lint Check

on:
  push:
    paths:
      - 'apps/backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/backend/**'

env:
  GH_TOKEN: ${{ github.token }} # ghコマンドを使用する場合はenvでtokenの設定が必要

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3

      - name: Install dependencies
        run: |
          gem install bundler
          cd apps/backend
          bundle install

      - name: Run RuboCop
        run: |
          cd apps/backend
          gh pr diff ${{ github.event.number }} --name-only |
          grep '\.rb$' |
          xargs -I {} sh -c '[ -f "{}" ] && echo "{}"' |
          xargs --no-run-if-empty bundle exec rubocop --force-exclusion
