name: RuboCop Lint Check

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/backend/**'

env:
  GH_TOKEN: ${{ github.token }} # ghコマンドを使用する場合はenvでtokenの設定が必要

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Ruby files
        id: check-ruby
        run: |
          cd apps/backend
          FILE_LIST=$(gh pr diff ${{ github.event.number }} --name-only)
          echo "ファイルリストのチェック $FILE_LIST"
          if [ -z "$FILE_LIST" ]; then
            echo "exitになった"
            exit 0
          else
            RUBY_FILES=$(echo "$FILE_LIST" | grep '\.rb$')
            echo "Ruby files"
            printf "%s\n" $RUBY_FILES
          fi

          if [ -z "$RUBY_FILES" ]; then
            echo "HAS_RUBY_FILES=false" >> $GITHUB_ENV
          else
            echo "HAS_RUBY_FILES=true" >> $GITHUB_ENV
          fi

      - name: Set up Ruby
        if: ${{ env.HAS_RUBY_FILES == 'true' }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3

      - name: Install dependencies
        if: ${{ env.HAS_RUBY_FILES == 'true' }}
        run: |
          gem install bundler
          cd apps/backend
          bundle install

      - name: Run RuboCop
        if: ${{ env.HAS_RUBY_FILES == 'true' }}
        run: |
          RUBY_FILES=$(gh pr diff ${{ github.event.number }} --name-only | grep '\.rb$')
          if [ -n "$RUBY_FILES" ]; then
            cd apps/backend
            echo "$RUBY_FILES" | sed 's|apps/backend/||' | xargs bundle exec rubocop --force-exclusion
          fi
