name: Check Wiki updates

on:
  schedule:
    - cron: '22 13 * * *' # This runs every day at 22:22 JST (which is 13:22 UTC)
    # - cron: '0 12 * * *' # This runs every day at 12:00 UTC

jobs:
  check-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout wiki repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki

    - name: Check updates
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add SortedWikiPages.md
        git commit -m "Update sorted wiki pages list"
        git push
