name: Check Wiki updates

on:
  schedule:
    - cron: '48 13 * * *' # This runs every day at 22:48 JST (which is 13:48 UTC)

jobs:
  check-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout wiki repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki

    - name: Check for old updates and add to the list
      run: |
        touch SortedWikiPages.md
        for file in .wiki/*; do
          if [[ "$(git log -1 --pretty=format:'%ai' -- "$file")" < "$(date -d '1 day ago' --utc +'%Y-%m-%dT%H:%M:%S')" ]]; then
            echo "$file" >> SortedWikiPages.md
          fi
        done

        # If changes exist, commit and push
        if [[ `git status --porcelain` ]]; then
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add SortedWikiPages.md
          git commit -m "Update sorted wiki pages list"
          git push origin master
        fi
