name: Check Wiki updates

on:
  schedule:
    - cron: '2 15 * * *' # This runs every day at 00:02 JST (which is 15:02 UTC)

jobs:
  check-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout wiki repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki

    - name: Check for old updates and add to the list
      run: |
        # Clear the SortedWikiPages.md file
        echo "" > SortedWikiPages.md

        # Add header to the file
        echo "| Pages | Last update |" >> SortedWikiPages.md
        echo "| --- | --- |" >> SortedWikiPages.md

        for file in *; do
          FILE_DATE=$(git log -1 --pretty=format:'%ai' -- "$file")
          ONE_DAY_AGO_DATE=$(date -d '1 day ago' --utc +'%Y-%m-%dT%H:%M:%S')

          # Debug output
          echo "File: $file, Last Update: $FILE_DATE, One Day Ago: $ONE_DAY_AGO_DATE"

          if [[ ! "$file" == "SortedWikiPages.md" ]] && [[ "$FILE_DATE" < "$ONE_DAY_AGO_DATE" ]]; then
            echo "| $file | $(echo $FILE_DATE | cut -d ' ' -f 1) |" >> SortedWikiPages.md
          fi
        done

        # If changes exist, commit and push
        if [[ `git status --porcelain` ]]; then
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add SortedWikiPages.md
          git commit -m "Update sorted wiki pages list"
          git push origin master
        fi
